### ISSUE TITLE
className prop not passed into resulting text node

### ISSUE THREAD

**Issue by muntact** [otissv/react-uikit-text#1]
the className prop applied to a Text component is not applied to the element generated by the text component. 

example to reproduce:

```
import Text from 'react-uikit-text';

....
// in the render:
<Text type="span" className="my-class-on-the-span">some-text</Text>
```

**Comment by muntact** [comment]
The following screenshot shows the className prop being applied from UIkitBase to Text, but not the generated element 

![screen shot 2017-04-27 at 9 48 01 am](https://cloud.githubusercontent.com/assets/13400754/25458794/7f810bc4-2b2f-11e7-8901-b98f5c23ce88.png)

**Comment by otissv** [comment]
Thanks for fixing this
